{% set name = 'copulas' %}
{% set version = '0.7.1.dev0' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - python >=3.6,<3.11
    - pytest-runner
    - matplotlib >=3.2.0,<4
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - scipy >=1.5.4,<2
  run:
    - python >=3.6,<3.11
    - matplotlib >=3.2.0,<4
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - scipy >=1.5.4,<2

about:
  home: "https://github.com/sdv-dev/Copulas"
  license: MIT
  license_family: MIT
  license_file:
  summary: "A python library for building different types of copulas and using them for sampling."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - sdv-dev
